name: Generate K8S-ECR-UPDATE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: italopenaforte/k8s-ecr-update
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}